//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagerWithDB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public long teacher_id { get; set; }
        public string teacher_code { get; set; }
        public long teacher_faculty_id { get; set; }
        public long teacher_matter_id { get; set; }
        public string teacher_role { get; set; }
        public string teacher_name { get; set; }
        public string teacher_surname { get; set; }
        public int teacher_age { get; set; }
        public string teacher_gender { get; set; }
        

        public Teachers(){}
        public Teachers(string teacher_code, long teacher_faculty_id, long teacher_matter_id, string teacher_role, string teacher_name, string teacher_surname, int teacher_age, string teacher_gender)
        {
            this.teacher_code = teacher_code;
            this.teacher_faculty_id = teacher_faculty_id;
            this.teacher_matter_id = teacher_matter_id;
            this.teacher_role = teacher_role;
            this.teacher_name = teacher_name;
            this.teacher_surname = teacher_surname;
            this.teacher_age = teacher_age;
            this.teacher_gender = teacher_gender;
           
        }

        public override string ToString()
        {
            return $"Teacher ID: {teacher_id} | Code: {teacher_code} | Faculty ID: {teacher_faculty_id} | " +
                   $"Matter ID: {teacher_matter_id} | Role: {teacher_role} | Name: {teacher_name} | " +
                   $"Surname: {teacher_surname} | Age: {teacher_age} | Gender: {teacher_gender}";
        }

    }
}
